# Global options
baseURL = "https://jonnybosnich.github.io/"
canonifyURLs = true
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
theme = "barks"
title = "Jonathan M. Bosnich"

# Main menu
[[menu.main]]
    name = "About"
    url  = "/pages/about"
    weight = 1
[[menu.main]]
    name = "Research"
    url  = "/pages/research"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url  = "/pages/teaching"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/pages/blog"
    weight = 2
[[menu.main]]
    name = "CV"
    url  = "/pages/CV"
    weight = 2
