# Global options
baseURL = "https://jmbosnich.github.io/"
canonifyURLs = true
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
theme = "barks"
title = "Jonathan M. Bosnich"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Main menu
[[menu.main]]
    name = "About"
    url  = "/pages/about"
    weight = 1
[[menu.main]]
    name = "Research"
    url  = "/pages/research"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url  = "/pages/teaching"
    weight = 3
#[[menu.main]]
#    name = "Blog"
#    url  = "/pages/blog"
#    weight = 4
[[menu.main]]
    name = "CV"
    url  = "/pages/CV"
    weight = 4

[[menu.main]]
    name = "Interests"
    url  = "/pages/other_interests"
    weight = 5

# Research pages
[[menu.main.research]]
    name = "Graduate projects"
    url = "/pages/grad_projects"

# Customizable parameters
[params]
    [param.social]
        [params.social.email]
            name = "Email"
            class = "fas fa-envelope"
            url = "mailto:jbosnich@luc.edu"
            weight = 1

        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/jmbosnich"
            weight = 2

        [params.social.linkedin]
            name = "LinkedIn"
            class = "fab fa-linkedin"
            url = "https://www.linkedin.com/in/jonathanbosnich/"
            weight = 3

        [params.colors]
            theme_color = "#333333"
            background_color = "#fcfbf9"
            text_color = "#333333"
            link_color = "#3f951a"
